#!/usr/bin/env python3
# pylint: disable=no-value-for-parameter

# Copyright (c) 2021 VMware, Inc. All rights reserved.

import subprocess

import click

import utils


@click.command()
@click.option("-D", "--duration", default="5m", show_default=True)
@click.option("--histfile", default="cyclictest.hist", show_default=True)
@click.option("--max-latency", "-h", "--histogram", default=500, show_default=True)
@click.option("-p", "--priority", default=99, show_default=True)
@click.option("-i", "--interval", default=100, show_default=True)
@click.option(
    "--dry-run", is_flag=True,
    help="Just print the command to run. So you can tweak and run it yourself "
         "manually later.")
def run(duration, histfile, max_latency, priority, interval, dry_run):
    cpus_count = len(list(utils.get_isol_cpus()))
    isol_cpus_text = utils.get_isol_cpus_text()

    cyclictest_args = [
        "taskset", "-c", isol_cpus_text, "cyclictest", "-t", str(cpus_count),
        "-m", "-p", str(priority), "-i", str(interval), "-h",
        str(max_latency), "-a", isol_cpus_text, "-D", duration,
        "--histfile", histfile]
    print(" ".join(cyclictest_args))
    if not dry_run:
        subprocess.run(cyclictest_args, check=True)


if __name__ == '__main__':
    run()
